# Generated by Django 3.0.3 on 2020-03-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(help_text='Date of the event', verbose_name='Date of the event')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('active', models.IntegerField(default=1, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brain.Animal')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
                'db_table': 'schedule',
            },
        ),
    ]
