# Generated by Django 3.0.3 on 2020-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='people_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
